#! /usr/bin/env ruby
# encoding: utf-8
require 'thor'

module EthilVan
   class CLI < Thor

      include Thor::Actions

      no_tasks do
         def load_environment
            require './config/env'
         end

         def load_app
            load_environment
            rrequire 'config/app'
         end
      end

      desc 'console',
            'Débute un shell ruby interactif avec l\'environnement chargé'
      def console
         load_environment
         require 'pry'
         Pry.config.prompt = [
            proc { |obj, nest_level, _| "#{obj} (#{nest_level}) >> " },
            proc { |obj, nest_level, _| "#{obj} (#{nest_level}) << " }
         ]
         EthilVan.pry
      end

      desc 'emoji', 'Installe les emoji dans le dossier "public/images/emoji"'
      def emoji
         load_environment
         rrequire 'lib/tasks/emoji_install'
         EthilVan::Emoji.install
      end

      desc 'migrate', 'Migre la base de données'
      def migrate
         load_environment
         require 'logger'
         ActiveRecord::Base.logger = Logger.new(STDOUT)
         ActiveRecord::Migration.verbose = true
         ActiveRecord::Migrator.migrate('database/migrations')
      end

      desc 'assets', 'Compile les assets'
      def assets
         load_environment
         rrequire 'lib/tasks/assets'
         EthilVan::Assets.compile
      end

      desc 'watch',
            'Surveille les changements des assets et recompile si besoin'
      def watch
         load_environment
         rrequire 'lib/tasks/assets'
         EthilVan::Assets.compile
         EthilVan::Assets.watch
      end

      desc 'test', 'Execute les test'
      def test
         ENV["RACK_ENV"] = 'test'
         load_app
         rrequire 'test/run'
      end
   end
end

EthilVan::CLI.start
