#! /usr/bin/env ruby
# encoding: utf-8

require "thor"

module EthilVan
   class CLI < Thor

      include Thor::Actions

      desc 'console',
            'Débute un shell ruby interactif avec l\'environnement chargé'
      def console
         run 'irb -r./config/env', verbose: false
      end
   end
end

EthilVan::CLI.start
