database:
   development:
      adapter:   mysql2
      encoding:  utf8
      reconnect: true
      pool:      5
      host:      localhost
      # A changer :
      username:  username
      password:  password
      database:  database
